owner: tusvml
repo: ping

sites:
  - name: TUS Homepage
    url: https://www.tus.ac.jp
  - name: VML Homepage
    url: https://www.rs.tus.ac.jp/vml
  - name: VML Blog
    url: https://tusvml.github.io/blog
